package com.jobson.market.auth.domain.model;

public enum Permission {
  CUSTOMER_PROFILE_ACCESS,
  CUSTOMER_SUBSCRIPTION_MANAGE_OWN,
  SELLER_CATALOG_MANAGE,
  SELLER_INVENTORY_MANAGE,
  SELLER_ORDER_FULFILL,
  SELLER_STAFF_MANAGE,
  SUPPORT_CUSTOMER_READ,
  SUPPORT_ORDER_ASSIST,
  PLATFORM_SELLER_REVIEW,
  AUTH_USER_ROLE_ASSIGN,
  AUTH_USER_ROLE_REVOKE
}
