sonar.projectKey=market-basket-platform
sonar.projectName=Market Basket Platform
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=services/auth-service/src/main/java
sonar.tests=services/auth-service/src/test/java
sonar.java.binaries=services/auth-service/target/classes
sonar.junit.reportPaths=services/auth-service/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=services/auth-service/target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=**/*Application.java,**/infrastructure/persistence/**,**/infrastructure/security/**,**/infrastructure/web/**
