server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/market_customer
    username: market
    password: market

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
