global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: market-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - auth-service:8080
          - customer-service:8081
          - seller-service:8087
          - catalog-service:8082
          - subscription-service:8083
          - order-service:8084
          - inventory-service:8085
          - notification-service:8086

  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets:
          - kong:8100

  - job_name: postgres
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: kafka
    static_configs:
      - targets:
          - kafka-exporter:9308
